version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      SECRET_KEY: "your_secret_key"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
